remote_theme: pages-themes/cayman@v0.2.0
title: YantraBuddhi - Gadget Mind
description: Blog on AI in Embedded Systems
plugins:
  - jekyll-remote-theme # add this line to the plugins list if you already have one
